//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CenturyLink_ArcApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("racorad30-scan.test.intranet")]
        public string Qual_Server {
            get {
                return ((string)(this["Qual_Server"]));
            }
            set {
                this["Qual_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DBMS")]
        public string AUTHENTICATION_MODE {
            get {
                return ((string)(this["AUTHENTICATION_MODE"]));
            }
            set {
                this["AUTHENTICATION_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("neisl01t_19")]
        public string Qual_DATABASE {
            get {
                return ((string)(this["Qual_DATABASE"]));
            }
            set {
                this["Qual_DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC")]
        public string Qual_USER_SWGISLOC {
            get {
                return ((string)(this["Qual_USER_SWGISLOC"]));
            }
            set {
                this["Qual_USER_SWGISLOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtlSwGis2020")]
        public string Qual_PASSWORD_SWGISLOC {
            get {
                return ((string)(this["Qual_PASSWORD_SWGISLOC"]));
            }
            set {
                this["Qual_PASSWORD_SWGISLOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sde.DEFAULT")]
        public string VERSION {
            get {
                return ((string)(this["VERSION"]));
            }
            set {
                this["VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1521")]
        public string Qual_PORT {
            get {
                return ((string)(this["Qual_PORT"]));
            }
            set {
                this["Qual_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SQM_Logs\\CLT_tempFiles\\")]
        public string TempFilesPath {
            get {
                return ((string)(this["TempFilesPath"]));
            }
            set {
                this["TempFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SQM_Logs\\")]
        public string LogPath {
            get {
                return ((string)(this["LogPath"]));
            }
            set {
                this["LogPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWTOMLOC.GDT_RD")]
        public string RoadsTableName {
            get {
                return ((string)(this["RoadsTableName"]));
            }
            set {
                this["RoadsTableName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.SERVICE_QUALIFICATION_MODEL")]
        public string ServicePolygonOutput {
            get {
                return ((string)(this["ServicePolygonOutput"]));
            }
            set {
                this["ServicePolygonOutput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DeadDesignations.txt")]
        public string DeadDesignationsFileName {
            get {
                return ((string)(this["DeadDesignationsFileName"]));
            }
            set {
                this["DeadDesignationsFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.GIS_LOCAL_CL_WIRE_CENTER")]
        public string WirecenterBoundaryName {
            get {
                return ((string)(this["WirecenterBoundaryName"]));
            }
            set {
                this["WirecenterBoundaryName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.NOBUILD")]
        public string Nobuild {
            get {
                return ((string)(this["Nobuild"]));
            }
            set {
                this["Nobuild"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.CL_PARCELS")]
        public string Parcels {
            get {
                return ((string)(this["Parcels"]));
            }
            set {
                this["Parcels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.GIS_LOCAL_LND_ADDRESS_LOC")]
        public string LNDAddress {
            get {
                return ((string)(this["LNDAddress"]));
            }
            set {
                this["LNDAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string InputPointTypes {
            get {
                return ((string)(this["InputPointTypes"]));
            }
            set {
                this["InputPointTypes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ConsiderTerminal {
            get {
                return ((string)(this["ConsiderTerminal"]));
            }
            set {
                this["ConsiderTerminal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ConiderTerminalPin {
            get {
                return ((string)(this["ConiderTerminalPin"]));
            }
            set {
                this["ConiderTerminalPin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string ConsiderLivingUnits {
            get {
                return ((string)(this["ConsiderLivingUnits"]));
            }
            set {
                this["ConsiderLivingUnits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.COPPER_LINE_OF_COUNT")]
        public string CopperLineofCountTable {
            get {
                return ((string)(this["CopperLineofCountTable"]));
            }
            set {
                this["CopperLineofCountTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.MATR_SHEATH_LOC_TERM_LOC102")]
        public string MAT_SheatWLOCTerminal {
            get {
                return ((string)(this["MAT_SheatWLOCTerminal"]));
            }
            set {
                this["MAT_SheatWLOCTerminal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RunMode {
            get {
                return ((string)(this["RunMode"]));
            }
            set {
                this["RunMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.LU_LATLON")]
        public string LU_Latlong {
            get {
                return ((string)(this["LU_Latlong"]));
            }
            set {
                this["LU_Latlong"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string Overlap_TerminalsonRoads {
            get {
                return ((string)(this["Overlap_TerminalsonRoads"]));
            }
            set {
                this["Overlap_TerminalsonRoads"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DWODS02PDB.qintra.com")]
        public string ODSDEV_Server {
            get {
                return ((string)(this["ODSDEV_Server"]));
            }
            set {
                this["ODSDEV_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sde:oracle11g:ODS_PROD")]
        public string ODSDEV_INSTANCE {
            get {
                return ((string)(this["ODSDEV_INSTANCE"]));
            }
            set {
                this["ODSDEV_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODS_PROD")]
        public string ODSDEV_DATABASE {
            get {
                return ((string)(this["ODSDEV_DATABASE"]));
            }
            set {
                this["ODSDEV_DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODSVIEW")]
        public string ODSDEV_USER {
            get {
                return ((string)(this["ODSDEV_USER"]));
            }
            set {
                this["ODSDEV_USER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ODS4View2019")]
        public string ODSDEV_PASSWORD {
            get {
                return ((string)(this["ODSDEV_PASSWORD"]));
            }
            set {
                this["ODSDEV_PASSWORD"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1523")]
        public string ODSDEV_PORT {
            get {
                return ((string)(this["ODSDEV_PORT"]));
            }
            set {
                this["ODSDEV_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.000100")]
        public string FiberBufferArea {
            get {
                return ((string)(this["FiberBufferArea"]));
            }
            set {
                this["FiberBufferArea"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.MAT_SHEATH_WITH_LOC_PIN")]
        public string MAT_SHEATH_WITH_LOC_PIN {
            get {
                return ((string)(this["MAT_SHEATH_WITH_LOC_PIN"]));
            }
            set {
                this["MAT_SHEATH_WITH_LOC_PIN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.SHEATH_SPLICE")]
        public string sheath_splice {
            get {
                return ((string)(this["sheath_splice"]));
            }
            set {
                this["sheath_splice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.SHEATH_WITH_LOC_TERMINAL")]
        public string SHEATH_WITH_LOC_TERMINAL {
            get {
                return ((string)(this["SHEATH_WITH_LOC_TERMINAL"]));
            }
            set {
                this["SHEATH_WITH_LOC_TERMINAL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.SQM_WORKFLOW")]
        public string SQM_WORKFLOW {
            get {
                return ((string)(this["SQM_WORKFLOW"]));
            }
            set {
                this["SQM_WORKFLOW"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("gpon_dev.sitesandjobs@gpon_prod_link")]
        public string SitesandJobs {
            get {
                return ((string)(this["SitesandJobs"]));
            }
            set {
                this["SitesandJobs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GPON.GPON_OC_ONT_SUMMARY_V@GPON_PROD_LINK")]
        public string GPON_OC_ONT_SUMMARY {
            get {
                return ((string)(this["GPON_OC_ONT_SUMMARY"]));
            }
            set {
                this["GPON_OC_ONT_SUMMARY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.LIVING_UNITS")]
        public string Livingunits {
            get {
                return ((string)(this["Livingunits"]));
            }
            set {
                this["Livingunits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.mat_mit_terminal_enclosure")]
        public string mit_terminal_enclosure {
            get {
                return ((string)(this["mit_terminal_enclosure"]));
            }
            set {
                this["mit_terminal_enclosure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA")]
        public string Qual_User_Qualschema {
            get {
                return ((string)(this["Qual_User_Qualschema"]));
            }
            set {
                this["Qual_User_Qualschema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(" CtlQual2020")]
        public string Qual_Password_QualSchema {
            get {
                return ((string)(this["Qual_Password_QualSchema"]));
            }
            set {
                this["Qual_Password_QualSchema"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.MIT_CABLE")]
        public string MIT_CABLE {
            get {
                return ((string)(this["MIT_CABLE"]));
            }
            set {
                this["MIT_CABLE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("swgisloc.sheath_with_loc")]
        public string sheath_with_loc {
            get {
                return ((string)(this["sheath_with_loc"]));
            }
            set {
                this["sheath_with_loc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.COPPER_SQM")]
        public string Copper_SQM {
            get {
                return ((string)(this["Copper_SQM"]));
            }
            set {
                this["Copper_SQM"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.COPPER_ADDRESSES")]
        public string Copper_Address {
            get {
                return ((string)(this["Copper_Address"]));
            }
            set {
                this["Copper_Address"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("swgisloc.living_units")]
        public string MONSTER {
            get {
                return ((string)(this["MONSTER"]));
            }
            set {
                this["MONSTER"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC.service_addresses")]
        public string service_addresses {
            get {
                return ((string)(this["service_addresses"]));
            }
            set {
                this["service_addresses"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.CUSTOM_PARCEL_DATA_LAYER")]
        public string CustomParcelLayer {
            get {
                return ((string)(this["CustomParcelLayer"]));
            }
            set {
                this["CustomParcelLayer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("QUAL_SCHEMA.REVIEW_COPPER")]
        public string ReviewCopper {
            get {
                return ((string)(this["ReviewCopper"]));
            }
            set {
                this["ReviewCopper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9775,9739,9763,9730,9776,9791,9762,9748,9789,9771,7170,9744,9732,9788,9768,9733,9" +
            "715,9353,9750,9790,9765,9761,7110,9780,9720,7180,9756,9742")]
        public string LanduseExcludeFTs {
            get {
                return ((string)(this["LanduseExcludeFTs"]));
            }
            set {
                this["LanduseExcludeFTs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GIS.LAND_USE")]
        public string LandUseTable {
            get {
                return ((string)(this["LandUseTable"]));
            }
            set {
                this["LandUseTable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("usded0000db.qintra.com")]
        public string LandUseDBServer {
            get {
                return ((string)(this["LandUseDBServer"]));
            }
            set {
                this["LandUseDBServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sde:oracle11g:USDED00011G")]
        public string LandUseDBInstance {
            get {
                return ((string)(this["LandUseDBInstance"]));
            }
            set {
                this["LandUseDBInstance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UNIPLTRD")]
        public string LandUseDBUserID {
            get {
                return ((string)(this["LandUseDBUserID"]));
            }
            set {
                this["LandUseDBUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtlAcc3ss")]
        public string LandUseDBPassword {
            get {
                return ((string)(this["LandUseDBPassword"]));
            }
            set {
                this["LandUseDBPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1547")]
        public string LanduseDBPort {
            get {
                return ((string)(this["LanduseDBPort"]));
            }
            set {
                this["LanduseDBPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("USDED000")]
        public string LanduseDBDatabase {
            get {
                return ((string)(this["LanduseDBDatabase"]));
            }
            set {
                this["LanduseDBDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CL_SUBADDRESS_POINT")]
        public string SubAddresses_Point {
            get {
                return ((string)(this["SubAddresses_Point"]));
            }
            set {
                this["SubAddresses_Point"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\USDDCWVUNQD01\\SharedFolder\\PxPointGeoCodeData\\")]
        public string gdxFilesPath {
            get {
                return ((string)(this["gdxFilesPath"]));
            }
            set {
                this["gdxFilesPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\GeoCode_LicFile\\QwestCommunicationsCompany7742.lic")]
        public string GeoCode_LicFile {
            get {
                return ((string)(this["GeoCode_LicFile"]));
            }
            set {
                this["GeoCode_LicFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("7742")]
        public string GeoCodeLicCode {
            get {
                return ((string)(this["GeoCodeLicCode"]));
            }
            set {
                this["GeoCodeLicCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sde:oracle11g:neisl01t_19")]
        public string Qual_INSTANCE {
            get {
                return ((string)(this["Qual_INSTANCE"]));
            }
            set {
                this["Qual_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public string ServiceBufferValue {
            get {
                return ((string)(this["ServiceBufferValue"]));
            }
            set {
                this["ServiceBufferValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public string ParcelProcessingPercentage1 {
            get {
                return ((string)(this["ParcelProcessingPercentage1"]));
            }
            set {
                this["ParcelProcessingPercentage1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99.5")]
        public string ParcelProcessingPercentage2 {
            get {
                return ((string)(this["ParcelProcessingPercentage2"]));
            }
            set {
                this["ParcelProcessingPercentage2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string BufferToConvex {
            get {
                return ((string)(this["BufferToConvex"]));
            }
            set {
                this["BufferToConvex"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1.5")]
        public string AvgRoadAreaMultiFactor {
            get {
                return ((string)(this["AvgRoadAreaMultiFactor"]));
            }
            set {
                this["AvgRoadAreaMultiFactor"] = value;
            }
        }
    }
}
