//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DbLibrary.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("racorad30-scan.test.intranet")]
        public string qual_Server {
            get {
                return ((string)(this["qual_Server"]));
            }
            set {
                this["qual_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sde:oracle11g:neisl01t_19")]
        public string qual_INSTANCE {
            get {
                return ((string)(this["qual_INSTANCE"]));
            }
            set {
                this["qual_INSTANCE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DBMS")]
        public string AUTHENTICATION_MODE {
            get {
                return ((string)(this["AUTHENTICATION_MODE"]));
            }
            set {
                this["AUTHENTICATION_MODE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("neisl01t_19")]
        public string qual_DATABASE {
            get {
                return ((string)(this["qual_DATABASE"]));
            }
            set {
                this["qual_DATABASE"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SWGISLOC")]
        public string USER_SWGISLOC {
            get {
                return ((string)(this["USER_SWGISLOC"]));
            }
            set {
                this["USER_SWGISLOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtlSwGis2020")]
        public string PASSWORD_SWGISLOC {
            get {
                return ((string)(this["PASSWORD_SWGISLOC"]));
            }
            set {
                this["PASSWORD_SWGISLOC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("sde.DEFAULT")]
        public string VERSION {
            get {
                return ((string)(this["VERSION"]));
            }
            set {
                this["VERSION"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1521")]
        public string Qual_PORT {
            get {
                return ((string)(this["Qual_PORT"]));
            }
            set {
                this["Qual_PORT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("qual_schema")]
        public string USER_QS {
            get {
                return ((string)(this["USER_QS"]));
            }
            set {
                this["USER_QS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CtlQual2020")]
        public string PASSWORD_QS {
            get {
                return ((string)(this["PASSWORD_QS"]));
            }
            set {
                this["PASSWORD_QS"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public string RunMode {
            get {
                return ((string)(this["RunMode"]));
            }
            set {
                this["RunMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("racorad09-scan.test.intranet")]
        public string lqmartinServer {
            get {
                return ((string)(this["lqmartinServer"]));
            }
            set {
                this["lqmartinServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lqdb002d_18")]
        public string lqmartinDatabase {
            get {
                return ((string)(this["lqmartinDatabase"]));
            }
            set {
                this["lqmartinDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("up2date")]
        public string lqmartinUserID {
            get {
                return ((string)(this["lqmartinUserID"]));
            }
            set {
                this["lqmartinUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lqma1n01")]
        public string lqmartinPassword {
            get {
                return ((string)(this["lqmartinPassword"]));
            }
            set {
                this["lqmartinPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1521")]
        public string lqPort {
            get {
                return ((string)(this["lqPort"]));
            }
            set {
                this["lqPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("racorad09-scan.test.intranet")]
        public string lqLfacsServer {
            get {
                return ((string)(this["lqLfacsServer"]));
            }
            set {
                this["lqLfacsServer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lqdw001_18")]
        public string lqLfacsDatabase {
            get {
                return ((string)(this["lqLfacsDatabase"]));
            }
            set {
                this["lqLfacsDatabase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("up2date")]
        public string lqLfacsUserID {
            get {
                return ((string)(this["lqLfacsUserID"]));
            }
            set {
                this["lqLfacsUserID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("lqma1n01")]
        public string lqLfacsPassword {
            get {
                return ((string)(this["lqLfacsPassword"]));
            }
            set {
                this["lqLfacsPassword"] = value;
            }
        }
    }
}
